DECLARE @HOJE as date
SET @HOJE = GETDATE()
DECLARE @CENTROCUSTO table (CC VARCHAR(MAX))

insert into @CENTROCUSTO values 
('01126.000002.025')
,('05287.000015.280')
,('05287.000016.280')
,('05356.000005.276')
,('05274.000017.258')
,('05285.000016.243')
;
with RATEIO as (SELECT * FROM  [HubDados].[CorporeRM].[TITMMOVRATCCU] WHERE CODCCUSTO COLLATE Latin1_General_CI_AS in (select CC from @CENTROCUSTO))
,TMOV AS (SELECT * FROM [HubDados].[CorporeRM].[TMOV] WHERE [STATUS] <> 'C' AND [DATAMOVIMENTO] BETWEEN DATEADD(DAY, -30, @HOJE) AND @HOJE AND CODTMV NOT LIKE '4.1%')
,CC AS (SELECT * FROM [FINANCA].[dbo].[CENTROCUSTO_DESCRICAO])
,DESC_MOV AS (SELECT * FROM [FINANCA].[dbo].[descricao_CODTMV])
,TVEN AS (SELECT * FROM [HubDados].[CorporeRM].[TVEN])


SELECT
FORMAT(A.DATACRIACAO,'d','pt-br') AS 'CRIADO EM'
,E.NOME AS 'VEN'
,B.CODCCUSTO
,C.PROJETO
,C.ACAO
,A.Historico
,A.CODTMV
,D.DESCMOV
,A.CODUSUARIO
,FORMAT(A.VALORBRUTO,'c','pt-br') AS 'BRUTO'
,CAMPOLIVRE1 AS 'CONTRATO'
,F.NOME AS 'VEN2'
,G.NOME AS 'VEN3'
,H.NOME AS 'VEN4'
,A.IDMOV
FROM TMOV A 
LEFT JOIN RATEIO B ON A.IDMOV = B.IDMOV 
INNER JOIN CC C ON B.CODCCUSTO COLLATE Latin1_General_CI_AS = C.CENTROCUSTO
LEFT JOIN DESC_MOV D ON A.CODTMV = D.CODTMV
LEFT JOIN TVEN E ON A.CODVEN1 = E.CODVEN
LEFT JOIN TVEN F ON A.CODVEN2 = F.CODVEN
LEFT JOIN TVEN G ON A.CODVEN3 = G.CODVEN
LEFT JOIN TVEN H ON A.CODVEN4 = H.CODVEN
order by A.DATACRIACAO DESC

