WITH VEN AS (SELECT * FROM [CorporeRM].[TVEN])

SELECT a.CODIGOCONTRATO
,A.NOME
,a.DATACONTRATO
,a.DATAINICIO
,a.DATAFIM
,c.NOME as 'GESTOR'
,d.NOME AS 'GERENTE'

,CASE WHEN CODSTACNT LIKE '00001' THEN 'Aberto'
		   WHEN CODSTACNT LIKE '00002' THEN 'Encerrado'
		   WHEN CODSTACNT LIKE '00003' THEN 'Pendente'
		   WHEN CODSTACNT LIKE '00005' THEN 'Cancelado'
		   WHEN CODSTACNT LIKE '00006' THEN 'Encerramento'
		   WHEN CODSTACNT LIKE '00008' THEN 'Encerrado Vigência'
			ELSE CODSTACNT END AS 'STATUS DO CONTRATO'

,CASE WHEN A.CODDEPARTAMENTO like '002.0001' THEN 'Araçatuba'
WHEN A.CODDEPARTAMENTO like '003.0001' THEN 'Bauru'
WHEN A.CODDEPARTAMENTO like '041.0001' THEN 'Vale do Ribeira'
WHEN A.CODDEPARTAMENTO like '010.0001' THEN 'Sorocaba'
WHEN A.CODDEPARTAMENTO like '009.0001' THEN 'São José do Rio Preto'
WHEN A.CODDEPARTAMENTO like '012.0001' THEN 'São Carlos'
WHEN A.CODDEPARTAMENTO like '011.0001' THEN 'Ribeirão Preto'
WHEN A.CODDEPARTAMENTO like '032.0001' THEN 'Alto Tietê'
WHEN A.CODDEPARTAMENTO like '040.0001' THEN 'Ourinhos'
WHEN A.CODDEPARTAMENTO like '026.0001' THEN 'Jundiaí'
WHEN A.CODDEPARTAMENTO like '018.0001' THEN 'Grande ABC'
WHEN A.CODDEPARTAMENTO like '016.0001' THEN 'Guaratinguetá'
WHEN A.CODDEPARTAMENTO like '038.0001' THEN 'Barretos'
WHEN A.CODDEPARTAMENTO like '027.0001' THEN 'Guarulhos'
WHEN A.CODDEPARTAMENTO like '020.0001' THEN 'Votuporanga'
WHEN A.CODDEPARTAMENTO like '006.0001' THEN 'Presidente Prudente'
WHEN A.CODDEPARTAMENTO like '008.0001' THEN 'São José dos Campos'
WHEN A.CODDEPARTAMENTO like '037.0001' THEN 'São João da Boa Vista'
WHEN A.CODDEPARTAMENTO like '014.0001' THEN 'Araraquara'
WHEN A.CODDEPARTAMENTO like '025.0001' THEN 'Capital Sul'
WHEN A.CODDEPARTAMENTO like '055.0001' THEN 'Capital Centro'
WHEN A.CODDEPARTAMENTO like '017.0001' THEN 'Franca'
WHEN A.CODDEPARTAMENTO like '034.0001' THEN 'Capital Leste I'
WHEN A.CODDEPARTAMENTO like '019.0001' THEN 'Piracicaba'
WHEN A.CODDEPARTAMENTO like '028.0001' THEN 'Osasco'
WHEN A.CODDEPARTAMENTO like '030.0001' THEN 'Capital Oeste'
WHEN A.CODDEPARTAMENTO like '005.0001' THEN 'Marília'
WHEN A.CODDEPARTAMENTO like '023.0001' THEN 'Capital Norte'
WHEN A.CODDEPARTAMENTO like '017' THEN 'Franca'
WHEN A.CODDEPARTAMENTO like '004.0001' THEN 'Campinas'
WHEN A.CODDEPARTAMENTO like '042.0001' THEN 'Sudoeste Paulista'
WHEN A.CODDEPARTAMENTO like '011' THEN 'Ribeirão Preto'
WHEN A.CODDEPARTAMENTO like '036.0001' THEN 'Botucatu'
WHEN A.CODDEPARTAMENTO like '052.0001' THEN 'Capital Leste II'
WHEN A.CODDEPARTAMENTO like '007.0001' THEN 'Baixada Santista'


else A.CODDEPARTAMENTO end as 'DEPARTAMENTO'

  FROM [HubDados].[CorporeRM].[TCNT] a
  inner join [HubDados].[CorporeRM].[TCNTCOMPL] b
  on a.IDCNT = b.IDCNT
  INNER JOIN VEN C
  ON A.CODVEN COLLATE SQL_Latin1_General_CP1_CI_AI = C.CODVEN
  INNER JOIN VEN D
  ON A.CODVEN2 COLLATE SQL_Latin1_General_CP1_CI_AI = D.CODVEN


  where b.MODALIDADE = 087
