use HubDados
go
with vw_status as (select * from [FINANCA].[dbo].[descricao_STATUS])
,CVEN AS (SELECT * FROM CorporeRM.TVEN)
,TMOV AS (SELECT * FROM CorporeRM.TMOV WHERE CODTMV IN ('1.1.01', '1.1.08') AND YEAR(DATACRIACAO) = YEAR(getdate()) and STATUS <> 'C')

SELECT 
 ROW_NUMBER() over(PARTITION BY A.IDMOV order by A.IDMOV) as contagem
,A.IDMOV
,NUMEROMOV
,CODTMV
,G.IDPRD
,H.NOMEFANTASIA
,b.desc_STATUS AS STATUS
,HISTORICO
,FORMAT(DATACRIACAO,'d','PT-BR') AS CRIADO_EM
,FORMAT(VALORBRUTOORIG,'C','PT-BR') AS VALOR
,FORMAT(G.VALORBRUTOITEM,'C','PT-BR') AS VALOR_ITEM
,UPPER(D.NOME) AS GESTOR
,UPPER(E.NOME) AS GERENTE

FROM TMOV a
INNER JOIN vw_status b
on a.STATUS = b.STATUS
LEFT JOIN CVEN C
ON A.CODVEN1 = C.CODVEN
LEFT JOIN CVEN D
ON A.CODVEN2 = D.CODVEN
LEFT JOIN CVEN E
ON A.CODVEN3 = E.CODVEN
LEFT JOIN CVEN F
ON A.CODVEN4 = F.CODVEN
LEFT JOIN [HubDados].[CorporeRM].[TITMMOV] G
ON A.IDMOV = G.IDMOV
LEFT JOIN [HubDados].[CorporeRM].[TPRD] H
ON G.IDPRD = H.IDPRD


order by DATACRIACAO desc